INSERT INTO autores (nombre)
VALUES 
('Epicuro'),
('Tales de Mileto'),
('Anaximandro'),
('Anaxímenes'),
('Pitágoras'),
('Heráclito'),
('Parménides'),
('Empédocles'),
('Anaxágoras'),
('Zenón de Elea'),
('Meliso de Samos'),
('Leucipo'),
('Demócrito'),
('Jenófanes'),
('Filolao'),
('Diógenes de Apolonia'),
('Sócrates'),
('Platón'),
('Aristóteles'),
('Antístenes'),
('Diógenes de Sinope'),
('Aristipo de Cirene'),
('Euclides de Mégara'),
('Fedón de Elis'),
('Espeusipo'),
('Jenócrates'),
('Zenón de Citio'),
('Crisipo'),
('Cleantes'),
('Pirrón de Elis'),
('Arcesilao'),
('Carnéades'),
('Diógenes de Babilonia'),
('Filón de Larisa'),
('Posidonio'),
('Lucrecio'),
('Cicerón'),
('Séneca'),
('Epicteto'),
('Marco Aurelio'),
('San Agustín de Hipona'),
('Boecio'),
('Anselmo de Canterbury'),
('Pedro Abelardo'),
('Tomás de Aquino'),
('Guillermo de Ockham'),
('Juan Duns Escoto'),
('Roscelino de Compiègne'),
('Moisés Maimónides'),
('Ramón Llull'),
('Juan de la Cruz'),
('Teresa de Ávila'),
('René Descartes'),
('Francis Bacon'),
('Baruch Spinoza'),
('John Locke'),
('Gottfried Wilhelm Leibniz'),
('George Berkeley'),
('David Hume'),
('Immanuel Kant'),
('Jean-Jacques Rousseau'),
('Voltaire'),
('Denis Diderot'),
('Montesquieu'),
('Jeremy Bentham'),
('Adam Smith'),
('Georg Wilhelm Friedrich Hegel'),
('Karl Marx'),
('Friedrich Nietzsche'),
('Sigmund Freud'),
('Edmund Husserl'),
('Martin Heidegger'),
('Jean-Paul Sartre'),
('Simone de Beauvoir'),
('Ludwig Wittgenstein'),
('Karl Popper'),
('Michel Foucault'),
('Richard Rorty'),
('Jacques Derrida'),
('Slavoj Žižek'),
('Martha Nussbaum'),
('Amartya Sen'),
('Julia Kristeva'),
('Bernard Stiegler'),
('Alain Badiou'),
('Antonio Negri'),
('Franco Berardi'),
('Arthur Schopenhauer'),
('Plotino'),
('Porfirio'),
('Jamblico'),
('Proclo'),
('Simónides de Ceos'),
('Diogenes Laercio'),
('Sexto Empírico'),
('Nicolás de Cusa'),
('Giordano Bruno'),
('Thomas Hobbes'),
('John Stuart Mill'),
('William James'),
('Ayn Rand'),
('Jacques Rancière'),
('Seyla Benhabib'),
('Donna Haraway'),
('Maurice Merleau-Ponty'),
('Alasdair MacIntyre'),
('Julian Baggini'),
('Richard Dawkins'),
('Thomas Nagel'),
('John Rawls'),
('Robert Nozick'),
('David Chalmers'),
('Hilary Putnam'),
('Robert Solomon'),
('Simone Weil'),
('G.E.M. Anscombe'),
('Gustavo Bueno'),
('José Ortega y Gasset'),
('Martin Buber');


-- Relacionar el primer problema con su autor
INSERT INTO problemas_autores (problema_id, autor_id)
VALUES 
(1, 1);  -- Problema 1 con Autor 1 (Epicuro)

-- Relacionar el segundo problema con su autor
INSERT INTO problemas_autores (problema_id, autor_id)
VALUES 
(2, 2);  -- Problema 2 con Autor 2 (Baruch Spinoza)
